### ISSUE TITLE
"&()"でスコープ、";"で区切る

### ISSUE THREAD

**Issue by yu-takaoka** [YouTakaoka/set-processor#18]
例1:
&(let s = {{}}; let t = {{{}}}; s + t)  # {{}, {{}}}
#s  # error
(途中で改行してもいいことにするとよりGood)

例2:
(let s = {{}}; let t = {{{}}}; s + t)  # {{}, {{}}}
s  # {{}}

**Comment by YouTakaoka** [comment]
'&()'だと次のようなとき困る:
&&() ←ぱっと見どっちか分からない

$()にする

**Comment by YouTakaoka** [comment]
区切り文字'|'にする
